Add ArgoCD config for HZ cluster
metacpan/metacpan-k8s pull request #23
Opened 2023-05-28 02:36 UTC by ssoriche

ArgoCD automatically deploys applications based on a git repo. When ArgoCD detects a change in the repo ArgoCD applies the manifests to the cluster, updating the state described within.

This change includes access to the ArgoCD UI with GitHub based authentication.

2023-06-01 10:43 UTC, ranguard requested changes
Just extra docs / info please

2023-06-01 10:43 UTC, ranguard commented on platform/argocd/hz/github_auth_secret.yaml
> +    clientId: AgCPn6zwguNItoy+ZnaCSRldRqj3UERCXnQq/Z7Y6EQAl4koMTl3lZi/ZVaYNb7VEyw5jUjF/TKIZ/+o5ax9phDN6/FIXun+75kDVU5vPI3z+eNqLmBfRz9aKT+sxv4HepLWv8fJ6y4zcp+NuYjWHJTKk/9DtfOurNcHtI71s/N1jHhtKzwpN5Gkl
Where does this cilientId / clientSecret come from - how is it generated? - some docs please

2023-06-01 10:43 UTC, ranguard commented on platform/argocd/patches/kustomization.yaml
> +      server.insecure: "true"
No clue what this is for, but is it ok to be insecure :) ?

2023-06-07 13:39 UTC, ssoriche commented on platform/argocd/patches/kustomization.yaml
> +      server.insecure: "true"
Yes because this is the Traefik ingress talking to the ArgoCD deployment internally in the cluster. The outside world to the Traefik ingress is encrypted.

2023-06-07 13:40 UTC, ssoriche commented on platform/argocd/hz/github_auth_secret.yaml
> +    clientId: AgCPn6zwguNItoy+ZnaCSRldRqj3UERCXnQq/Z7Y6EQAl4koMTl3lZi/ZVaYNb7VEyw5jUjF/TKIZ/+o5ax9phDN6/FIXun+75kDVU5vPI3z+eNqLmBfRz9aKT+sxv4HepLWv8fJ6y4zcp+NuYjWHJTKk/9DtfOurNcHtI71s/N1jHhtKzwpN5Gkl
It's generated the same as all the other secrets and stored in the same place, but I've added documentation on how ArgoCD is configured into the docs directory as part of this PR.

2023-06-08 20:58 UTC, ranguard approved these changes
Thanks - I'd not seen the credentials PR

2023-06-08 20:59 UTC, merged